# Generated by Django 3.1.7 on 2021-03-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('foot', 10), ('bike', 15), ('car', 50)], max_length=10)),
                ('regions', models.JSONField()),
                ('working_hours', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('weight', models.FloatField()),
                ('region', models.IntegerField()),
                ('delivery_hours', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='CourierOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=100)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.courier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.order')),
            ],
        ),
    ]
