# Generated by Django 3.1.7 on 2021-03-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20210310_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='id',
            new_name='courier_id',
        ),
        migrations.RenameField(
            model_name='courier',
            old_name='type',
            new_name='courier_type',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='order_id',
        ),
    ]
