# Generated by Django 3.1.7 on 2021-03-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_auto_20210311_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courierorder',
            name='status',
        ),
        migrations.AddField(
            model_name='courierorder',
            name='assign_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='courierorder',
            name='complete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
