# Generated by Django 3.1.7 on 2021-03-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_auto_20210315_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierorder',
            name='assign_time',
            field=models.DateTimeField(),
        ),
    ]
