# Generated by Django 3.1.7 on 2021-03-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_courierorder__cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierorder',
            name='_cost',
            field=models.IntegerField(blank=True, db_column='cost', default=None, null=True),
        ),
    ]
